const orderTypes ={
SAVE_ORDER_HISTORY_START:'SAVE_ORDER_HISTORY_START',
GET_USER_ORDER_HISTORY_START:'GET_USER_HISTORY_START',
SET_USER_ORDER_HISTORY:'SET_USER_ORDER_HISTORY',
GET_ORDER_DETAIL_START:'GET_ORDER_DETAIL_START',
SET_ORDER_DETAIL:'SET_ORDER_DETAIL',
GET_SELLER_ORDER_HISTORY:'GET_SELLER_ORDER_HISTORY',
SET_SELLER_ORDER_HISTORY:'SET_SELLER_ORDER_HISTORY',
UPDATE_ORDER:'UPDATE_ORDER',//added now
SET_UPDATED_ORDER: 'SET_UPDATED_ORDER'
}
export default orderTypes;